### ISSUE TITLE
Display a response when search result = null

### ISSUE THREAD

**Issue by abhiyerra** [chimera/sonomafireinfo.org#11]
Currently, when a user enters a search term in the search field at the top of subpages (e.g. http://sonomafireinfo.org/#/services), results only display if there's a match. When there is no match, the page remains blank and there's no user feedback, which is unclear to the user if their search is working or not. Recommend adding a "We couldn't find any results matching your search. We recommend trying a different search term, or visiting a different resource page."

Respond To: iamjsand@gmail.com

**Comment by danawoodman** [comment]
Done!

![](https://cl.ly/nCoK/Screen%20Shot%202017-10-20%20at%2010.07.27%20AM.png)
