### ISSUE TITLE
"Help Us Improve" button

### ISSUE THREAD

**Issue by nicole-clark** [chimera/sonomafireinfo.org#21]

**Comment by nicole-clark** [comment]
Hi Terry, I'm imagining on the contact us page three separate action items:

1) the "general questions, want to volunteer" that leads to the gmail
2) the information lead form
3) a "help us improve" button that allows people to comment on their user experience, maybe give us a little bit more insight into people's experience of the website.

Basically, the contact us page feels very sloppy to me. I want people to understand there are separate channels to get us the information we need since we have different teams working on different aspects of the project.

**Comment by danawoodman** [comment]
@TerryBeyak see the `<ContactPage>` component
