### ISSUE TITLE
Improve the embedded calendar

### ISSUE THREAD

**Issue by rtyler** [chimera/sonomafireinfo.org#24]
I need to investigate whether or not I can improve the embedded calendar widget from wirtable to be a bit more legible.

Failing that we might need to hack up our own custom calendar (BLECH)

**Comment by neufuture** [comment]
Yes i agree, though i'd say lower priority. I think we might consider agenda view as a better options with a link to iCal or something like that

example
https://www.scrubly.com/blog/wp-content/uploads/2014/02/feb17_21.jpg

**Comment by rtyler** [comment]
@neufuture it looks like changing the views in Airtable changes the embed, so I tweaked those.
