### ISSUE TITLE
Include "Last Updated" column with date picker on tabs that need it

### ISSUE THREAD

**Issue by theecrit** [chimera/sonomafireinfo.org#28]
The following sections need a "Last Updated" column with date picker:

- Shelter Contacts
- Recovery
- Medical
- Schools (maybe not necessary?)
- District (maybe not necessary?)
- Social Media
- Evacuations
- Upcoming Events

**Comment by danawoodman** [comment]
@theecrit feel free to add the column is you have permissions.
