### ISSUE TITLE
Please De-Prioritize FB + Twitter

### ISSUE THREAD

**Issue by ErinRosie** [chimera/sonomafireinfo.org#29]
Can we move these below the calendar? Wanting to avoid driving people away from the site or setting an expectation that the social feeds offer more current data than the site. Especially on mobile.

**Comment by ErinRosie** [comment]
In fact, maybe we can just move FB + IG icons side-by-side to the bottom of the page (or upper corner), as most sites handle them? I'd like to get away from committing social handles to the burden of streaming updates.

I'll stop talking now.

**Comment by rtyler** [comment]
I think this is reasonable, i'll get a pull request queued up

**Comment by rtyler** [comment]
Perhaps solved better by @danawoodman with #27
