### ISSUE TITLE
Notes column in Spanish tab

### ISSUE THREAD

**Issue by abhiyerra** [chimera/sonomafireinfo.org#5]
Push "Notas" column in Spanish tab live onto the site. Currently the column exists in Airtable, but is not showing up on the website. Formatting should match "Notes" from other tabs (smaller text, grey)

Respond To: sheenastevens@gmail.com

**Comment by danawoodman** [comment]
Done! 

![](https://cl.ly/nCqb/Screen%20Shot%202017-10-20%20at%2012.19.43%20PM.png)

@abhiyerra who is replying to people when done?
