### ISSUE TITLE
Hide No Need Facilities

### ISSUE THREAD

**Issue by abhiyerra** [chimera/sonomafireinfo.org#8]
Facilities with no needs = noise, but things change.  Can those with no needs either be hidden, grayed out, and or separate at bottom?

Respond To: matt.chisam@gmail.com

**Comment by neufuture** [comment]
Shelters are not really accepting new volunteers or donations. I'm thinking we might remove those fields entirely. The priority would be to sort the closed shelters to the bottom of the list

**Comment by danawoodman** [comment]
@abhiyerra is this your task? I'll assign to you for now

**Comment by danawoodman** [comment]
Moving to #17
